In [3]:
import pandas as pd

In [4]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [5]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [6]:
cr.shape

(981, 13)

In [7]:
cr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [8]:
#how to select individual columns

In [9]:
cr.ApplicantIncome.describe()

count      981.000000
mean      5179.795107
std       5695.104533
min          0.000000
25%       2875.000000
50%       3800.000000
75%       5516.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [10]:
cr['ApplicantIncome'].describe()

count      981.000000
mean      5179.795107
std       5695.104533
min          0.000000
25%       2875.000000
50%       3800.000000
75%       5516.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [11]:
cr.Gender.describe()

count      957
unique       2
top       Male
freq       775
Name: Gender, dtype: object

In [12]:
cr.Property_Area.describe()

count           981
unique            3
top       Semiurban
freq            349
Name: Property_Area, dtype: object

In [13]:
cr.Gender.value_counts()

Male      775
Female    182
Name: Gender, dtype: int64

In [14]:
cr.Property_Area.value_counts()

Semiurban    349
Urban        342
Rural        290
Name: Property_Area, dtype: int64

In [15]:
cr.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,956.000000,981.000000,981.000000,954.000000,961.000000,902.000000
mean,0.881799,5179.795107,1601.916330,142.511530,342.201873,0.835920
std,1.255623,5695.104533,2718.772806,77.421743,65.100602,0.370553
min,0.000000,0.000000,0.000000,9.000000,6.000000,0.000000
25%,0.000000,2875.000000,0.000000,100.000000,360.000000,1.000000
50%,0.000000,3800.000000,1110.000000,126.000000,360.000000,1.000000
75%,2.000000,5516.000000,2365.000000,162.000000,360.000000,1.000000
max,4.000000,81000.000000,41667.000000,700.000000,480.000000,1.000000

In [16]:
cr.describe(include='all')

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,981,957,978,956.000000,981,926,981.000000,981.000000,954.000000,961.000000,902.000000,981,981
unique,981,2,2,NaN,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP002139,Male,Yes,NaN,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,775,631,NaN,763,807,NaN,NaN,NaN,NaN,NaN,349,712
mean,NaN,NaN,NaN,0.881799,NaN,NaN,5179.795107,1601.916330,142.511530,342.201873,0.835920,NaN,NaN
std,NaN,NaN,NaN,1.255623,NaN,NaN,5695.104533,2718.772806,77.421743,65.100602,0.370553,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,9.000000,6.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,0.000000,NaN,NaN,2875.000000,0.000000,100.000000,360.000000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,0.000000,NaN,NaN,3800.000000,1110.000000,126.000000,360.000000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,2.000000,NaN,NaN,5516.000000,2365.000000,162.000000,360.000000,1.000000,NaN,NaN
max,NaN,NaN,NaN,4.000000,NaN,NaN,81000.000000,41667.000000,700.000000,480.000000,1.000000,NaN,NaN

In [17]:
cr.Gender.describe()

count      957
unique       2
top       Male
freq       775
Name: Gender, dtype: object

In [18]:
cr.Gender.value_counts()

Male      775
Female    182
Name: Gender, dtype: int64

In [19]:
#how to find the Null in the dataFrame

In [20]:
cr1 = cr.dropna()

In [21]:
cr1.shape

(769, 13)

In [22]:
cr.shape

(981, 13)

In [23]:
cr.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [24]:
cr.Credit_History.value_counts()

1.0    754
0.0    148
Name: Credit_History, dtype: int64

In [25]:
cr.Credit_History.value_counts()

1.0    754
0.0    148
Name: Credit_History, dtype: int64

In [26]:
cr.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [27]:
cr.Credit_History = cr.Credit_History.fillna(1)
cr.Gender = cr.Gender.fillna('Male')
cr.Married = cr.Married.fillna('No')
cr.Dependents = cr.Dependents.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna('Yes')
cr.LoanAmount = cr.LoanAmount.fillna(cr.LoanAmount.mean())
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())

In [28]:
cr.Dependents.value_counts()

0.0    570
2.0    160
1.0    160
4.0     90
3.0      1
Name: Dependents, dtype: int64

In [29]:
cr.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [30]:
# Lets do the slicing dicing of DataFrame
# how to select rows and cols also based on requirement

In [31]:
cr.iloc[ [0,9,99,399,499], [0,2,5,8,9]] #iloc Stands for index Location.

      Loan_ID Married Self_Employed  LoanAmount  Loan_Amount_Term
0    LP001002      No            No   142.51153             360.0
9    LP001020     Yes            No   349.00000             360.0
99   LP001343     Yes            No   131.00000             360.0
399  LP002287      No            No   103.00000             360.0
499  LP002602      No            No   209.00000             360.0

In [32]:
cr2 = cr.iloc[ [0,9,99,399,499], [0,2,5,8,9]]

In [33]:
cr2

      Loan_ID Married Self_Employed  LoanAmount  Loan_Amount_Term
0    LP001002      No            No   142.51153             360.0
9    LP001020     Yes            No   349.00000             360.0
99   LP001343     Yes            No   131.00000             360.0
399  LP002287      No            No   103.00000             360.0
499  LP002602      No            No   209.00000             360.0

In [34]:
cr.iloc[[0,9,99,399,499],:]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,142.51153,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.0,349.00000,360.0,1.0,Semiurban,N
99,LP001343,Male,Yes,0.0,Graduate,No,1759,3541.0,131.00000,360.0,1.0,Semiurban,Y
399,LP002287,Female,No,0.0,Graduate,No,1500,1800.0,103.00000,360.0,0.0,Semiurban,N
499,LP002602,Male,No,0.0,Graduate,No,6283,4416.0,209.00000,360.0,0.0,Rural,N

In [35]:
cr.iloc[:,[1,4,6]]

    Gender     Education  ApplicantIncome
0     Male      Graduate             5849
1     Male      Graduate             4583
2     Male      Graduate             3000
3     Male  Not Graduate             2583
4     Male      Graduate             6000
..     ...           ...              ...
976   Male  Not Graduate             4009
977   Male      Graduate             4158
978   Male      Graduate             3250
979   Male      Graduate             5000
980   Male      Graduate             9200

[981 rows x 3 columns]

# till now we have selected dta on index position but we can also select based on names

In [36]:
cr4 = cr.loc[:,['Gender','Education','ApplicantIncome']]

In [37]:
cr4.head()

  Gender     Education  ApplicantIncome
0   Male      Graduate             5849
1   Male      Graduate             4583
2   Male      Graduate             3000
3   Male  Not Graduate             2583
4   Male      Graduate             6000

In [38]:
cr4.shape

(981, 3)

In [39]:
# lets select record based on the condition

In [40]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,142.51153,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.00000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.00000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.00000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.00000,360.0,1.0,Urban,Y

In [41]:
cr5 = cr[cr.ApplicantIncome >= 3000]

In [42]:
cr5.shape

(703, 13)

In [43]:
cr.shape

(981, 13)

In [44]:
cr5.ApplicantIncome.describe()

count      703.000000
mean      6321.937411
std       6367.785835
min       3000.000000
25%       3648.000000
50%       4583.000000
75%       6391.500000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [45]:
cr5.ApplicantIncome.min()

3000

In [46]:
cr6 = cr[(cr.ApplicantIncome > 3000) & (cr.Education == 'Graduate')]

In [47]:
cr6.Education.value_counts()

Graduate    573
Name: Education, dtype: int64

In [48]:
# drop Function can be used to drop our columns

In [49]:
cr7 = cr.drop(['Loan_ID'], axis = 1)
#axis = 1 implies i want to run drop function on columns

In [50]:
cr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [51]:
#drop can be used to drop more than one columns

In [52]:
cr32 = cr.drop(['Loan_ID','Gender','ApplicantIncome'], axis = 1)

In [53]:
cr32

,Married,Dependents,Education,Self_Employed,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,No,0.0,Graduate,No,0.0,142.51153,360.0,1.0,Urban,Y
1,Yes,1.0,Graduate,No,1508.0,128.00000,360.0,1.0,Rural,N
2,Yes,0.0,Graduate,Yes,0.0,66.00000,360.0,1.0,Urban,Y
3,Yes,0.0,Not Graduate,No,2358.0,120.00000,360.0,1.0,Urban,Y
4,No,0.0,Graduate,No,0.0,141.00000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
976,Yes,4.0,Not Graduate,Yes,1777.0,113.00000,360.0,1.0,Urban,Y
977,Yes,0.0,Graduate,No,709.0,115.00000,360.0,1.0,Urban,Y
978,No,0.0,Graduate,No,1993.0,126.00000,360.0,1.0,Semiurban,Y
979,Yes,0.0,Graduate,No,2393.0,158.00000,360.0,1.0,Rural,N
980,No,0.0,Graduate,Yes,0.0,98.00000,180.0,1.0,Rural,Y

In [54]:
cr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

## Groupby

Problem Statement(If i want to analise is there any difference in-come of graduates and Non Graduates)

In [55]:
# group_by = cr.groupby([cr.ApplicantIncome, cr.Education])

In [56]:
cr.groupby('Education').ApplicantIncome.mean()

Education
Graduate        5602.440367
Not Graduate    3700.536697
Name: ApplicantIncome, dtype: float64

In [57]:
cr.groupby('Education').ApplicantIncome.mean().round(2) #roud it to no of decimal postions

Education
Graduate        5602.44
Not Graduate    3700.54
Name: ApplicantIncome, dtype: float64

In [58]:
# groupby more tahn one columns

In [59]:
cr.groupby('Gender').ApplicantIncome.mean()

Gender
Female    4458.906593
Male      5344.002503
Name: ApplicantIncome, dtype: float64

In [60]:
cr.groupby(['Education','Gender']).ApplicantIncome.mean().round()

Education     Gender
Graduate      Female    4598.0
              Male      5844.0
Not Graduate  Female    3853.0
              Male      3672.0
Name: ApplicantIncome, dtype: float64

In [61]:
cr.groupby(['Education','Gender']).ApplicantIncome.median().round()

Education     Gender
Graduate      Female    3666.0
              Male      4116.0
Not Graduate  Female    3016.0
              Male      3345.0
Name: ApplicantIncome, dtype: float64

In [62]:
cr.groupby(['Education','Gender','Self_Employed']).ApplicantIncome.median().round()

Education     Gender  Self_Employed
Graduate      Female  No               3655.0
                      Yes              4166.0
              Male    No               3973.0
                      Yes              5417.0
Not Graduate  Female  No               2599.0
                      Yes              6166.0
              Male    No               3276.0
                      Yes              3808.0
Name: ApplicantIncome, dtype: float64

In [63]:
cr.groupby('Education').mean().round() # mean for each and every Numeric columns

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
Education,,,,,,
Graduate,1.0,5602.0,1690.0,149.0,343.0,1.0
Not Graduate,1.0,3701.0,1295.0,119.0,339.0,1.0

# Lets combine Groupby with Aggregate

In [64]:
cr.groupby(['Education']).ApplicantIncome.agg(['mean','max','min','median','count','std']).round()

                mean    max  min  median  count     std
Education
Graduate      5602.0  81000    0    4000    763  6295.0
Not Graduate  3701.0  18165    0    3333    218  2121.0

In [65]:
cr.groupby(['Education','Gender']).ApplicantIncome.agg(['mean','max','min','median','count','std']).round()

                       mean    max  min  median  count     std
Education    Gender
Graduate     Female  4598.0  19484  416  3666.0    148  3119.0
             Male    5844.0  81000    0  4116.0    615  6823.0
Not Graduate Female  3853.0  18165    0  3016.0     34  3790.0
             Male    3672.0  13083  570  3345.0    184  1655.0

In [66]:
pd.set_option('display.max_columns',None)
cr.groupby(['Education']).agg(['mean','max','min','median','count','std']).round()

             Dependents                             ApplicantIncome         \
                   mean  max  min median count  std            mean    max
Education
Graduate            1.0  4.0  0.0    0.0   763  1.0          5602.0  81000
Not Graduate        1.0  4.0  0.0    0.0   218  1.0          3701.0  18165

                                      CoapplicantIncome                        \
             min median count     std              mean      max  min  median
Education
Graduate       0   4000   763  6295.0            1690.0  41667.0  0.0  1030.0
Not Graduate   0   3333   218  2121.0            1295.0  13983.0  0.0  1271.0

                           LoanAmount                                  \
             count     std       mean    max   min median count   std
Education
Graduate       763  2967.0      149.0  700.0   9.0  132.0   763  83.0
Not Graduate   218  1532.0      119.0  279.0  25.0  120.0   218  38.0

             Loan_Amount_Term                                 Credit_History  \
                         mean    max   min median count   std           mean
Education
Graduate                343.0  480.0   6.0  360.0   763  63.0            1.0
Not Graduate            339.0  480.0  36.0  360.0   218  69.0            1.0


              max  min median count  std
Education
Graduate      1.0  0.0    1.0   763  0.0
Not Graduate  1.0  0.0    1.0   218  0.0

In [67]:
pd.set_option('display.max_rows',None)

In [68]:
cr

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.000000,142.51153,360.000000,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.000000,128.00000,360.000000,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.000000,66.00000,360.000000,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.000000,120.00000,360.000000,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.000000,141.00000,360.000000,1.0,Urban,Y
5,LP001011,Male,Yes,2.0,Graduate,Yes,5417,4196.000000,267.00000,360.000000,1.0,Urban,Y
6,LP001013,Male,Yes,0.0,Not Graduate,No,2333,1516.000000,95.00000,360.000000,1.0,Urban,Y
7,LP001014,Male,Yes,4.0,Graduate,No,3036,2504.000000,158.00000,360.000000,0.0,Semiurban,N
8,LP001018,Male,Yes,2.0,Graduate,No,4006,1526.000000,168.00000,360.000000,1.0,Urban,Y
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.000000,349.00000,360.000000,1.0,Semiurban,N
10,LP001024,Male,Yes,2.0,Graduate,No,3200,700.000000,70.00000,360.000000,1.0,Urban,Y
11,LP001027,Male,Yes,2.0,Graduate,Yes,2500,1840.000000,109.00000,360.000000,1.0,Urban,Y
12,LP001028,Male,Yes,2.0,Graduate,No,3073,8106.000000,200.00000,360.000000,1.0,Urban,Y
13,LP001029,Male,No,0.0,Graduate,No,1853,2840.000000,114.00000,360.000000,1.0,Rural,N
14,LP001030,Male,Yes,2.0,Graduate,No,1299,1086.000000,17.00000,120.000000,1.0,Urban,Y
15,LP001032,Male,No,0.0,Graduate,No,4950,0.000000,125.00000,360.000000,1.0,Urban,Y
16,LP001034,Male,No,1.0,Not Graduate,No,3596,0.000000,100.00000,240.000000,1.0,Urban,Y
17,LP001036,Female,No,0.0,Graduate,No,3510,0.000000,76.00000,360.000000,0.0,Urban,N
18,LP001038,Male,Yes,0.0,Not Graduate,No,4887,0.000000,133.00000,360.000000,1.0,Rural,N
19,LP001041,Male,Yes,0.0,Graduate,Yes,2600,3500.000000,115.00000,342.201873,1.0,Urban,Y
20,LP001043,Male,Yes,0.0,Not Graduate,No,7660,0.000000,104.00000,360.000000,0.0,Urban,N
21,LP001046,Male,Yes,1.0,Graduate,No,5955,5625.000000,315.00000,360.000000,1.0,Urban,Y
22,LP001047,Male,Yes,0.0,Not Graduate,No,2600,1911.000000,116.00000,360.000000,0.0,Semiurban,N
23,LP001050,Male,Yes,2.0,Not Graduate,No,3365,1917.000000,112.00000,360.000000,0.0,Rural,N
24,LP001052,Male,Yes,1.0,Graduate,Yes,3717,2925.000000,151.00000,360.000000,1.0,Semiurban,N
25,LP001066,Male,Yes,0.0,Graduate,Yes,9560,0.000000,191.00000,360.000000,1.0,Semiurban,Y
26,LP001068,Male,Yes,0.0,Graduate,No,2799,2253.000000,122.00000,360.000000,1.0,Semiurban,Y
27,LP001073,Male,Yes,2.0,Not Graduate,No,4226,1040.000000,110.00000,360.000000,1.0,Urban,Y
28,LP001086,Male,No,0.0,Not Graduate,No,1442,0.000000,35.00000,360.000000,1.0,Urban,N
29,LP001087,Female,No,2.0,Graduate,Yes,3750,2083.000000,120.00000,360.000000,1.0,Semiurban,Y
30,LP001091,Male,Yes,1.0,Graduate,Yes,4166,3369.000000,201.00000,360.000000,1.0,Urban,N
31,LP001095,Male,No,0.0,Graduate,No,3167,0.000000,74.00000,360.000000,1.0,Urban,N
32,LP001097,Male,No,1.0,Graduate,Yes,4692,0.000000,106.00000,360.000000,1.0,Rural,N
33,LP001098,Male,Yes,0.0,Graduate,No,3500,1667.000000,114.00000,360.000000,1.0,Semiurban,Y
34,LP001100,Male,No,4.0,Graduate,No,12500,3000.000000,320.00000,360.000000,1.0,Rural,N
35,LP001106,Male,Yes,0.0,Graduate,No,2275,2067.000000,142.51153,360.000000,1.0,Urban,Y
36,LP001109,Male,Yes,0.0,Graduate,No,1828,1330.000000,100.00000,342.201873,0.0,Urban,N
37,LP001112,Female,Yes,0.0,Graduate,No,3667,1459.000000,144.00000,360.000000,1.0,Semiurban,Y
38,LP001114,Male,No,0.0,Graduate,No,4166,7210.000000,184.00000,360.000000,1.0,Urban,Y
39,LP001116,Male,No,0.0,Not Graduate,No,3748,1668.000000,110.00000,360.000000,1.0,Semiurban,Y
40,LP001119,Male,No,0.0,Graduate,No,3600,0.000000,80.00000,360.000000,1.0,Urban,N
41,LP001120,Male,No,0.0,Graduate,No,1800,1213.000000,47.00000,360.000000,1.0,Urban,Y
42,LP001123,Male,Yes,0.0,Graduate,No,2400,0.000000,75.00000,360.000000,1.0,Urban,Y
43,LP001131,Male,Yes,0.0,Graduate,No,3941,2336.000000,134.00000,360.000000,1.0,Semiurban,Y
44,LP001136,Male,Yes,0.0,Not Graduate,Yes,4695,0.000000,96.00000,342.201873,1.0,Urban,Y
45,LP001137,Female,No,0.0,Graduate,No,3410,0.000000,88.00000,342.201873,1.0,Urban,Y
46,LP001138,Male,Yes,1.0,Graduate,No,5649,0.000000,44.00000,360.000000,1.0,Urban,Y
47,LP001144,Male,Yes,0.0,Graduate,No,5821,0.000000,144.00000,360.000000,1.0,Urban,Y
48,LP001146,Female,Yes,0.0,Graduate,No,2645,3440.000000,120.00000,360.000000,0.0,Urban,N
49,LP001151,Female,No,0.0,Graduate,No,4000,2275.000000,144.00000,360.000000,1.0,Semiurban,Y
50,LP001155,Female,Yes,0.0,Not Graduate,No,1928,1644.000000,100.00000,360.000000,1.0,Semiurban,Y
51,LP001157,Female,No,0.0,Graduate,No,3086,0.000000,120.00000,360.000000,1.0,Semiurban,Y
52,LP001164,Female,No,0.0,Graduate,No,4230,0.000000,112.00000,360.000000,1.0,Semiurban,N
53,LP001179,Male,Yes,2.0,Graduate,No,4616,0.000000,134.00000,360.000000,1.0,Urban,N
54,LP001186,Female,Yes,1.0,Graduate,Yes,11500,0.000000,286.00000,360.000000,0.0,Urban,N
55,LP001194,Male,Yes,2.0,Graduate,No,2708,1167.000000,97.00000,360.000000,1.0,Semiurban,Y
56,LP001195,Male,Yes,0.0,Graduate,No,2132,1591.000000,96.00000,360.000000,1.0,Semiurban,Y
57,LP001197,Male,Yes,0.0,Graduate,No,3366,2200.000000,135.00000,360.000000,1.0,Rural,N
58,LP001198,Male,Yes,1.0,Graduate,No,8080,2250.000000,180.00000,360.000000,1.0,Urban,Y
59,LP001199,Male,Yes,2.0,Not Graduate,No,3357,2859.000000,144.00000,360.000000,1.0,Urban,Y
60,LP001205,Male,Yes,0.0,Graduate,No,2500,3796.000000,120.00000,360.000000,1.0,Urban,Y
61,LP001206,Male,Yes,4.0,Graduate,No,3029,0.000000,99.00000,360.000000,1.0,Urban,Y
62,LP001207,Male,Yes,0.0,Not Graduate,Yes,2609,3449.000000,165.00000,180.000000,0.0,Rural,N
63,LP001213,Male,Yes,1.0,Graduate,No,4945,0.000000,142.51153,360.000000,0.0,Rural,N
64,LP001222,Female,No,0.0,Graduate,No,4166,0.000000,116.00000,360.000000,0.0,Semiurban,N
65,LP001225,Male,Yes,0.0,Graduate,No,5726,4595.000000,258.00000,360.000000,1.0,Semiurban,N
66,LP001228,Male,No,0.0,Not Graduate,No,3200,2254.000000,126.00000,180.000000,0.0,Urban,N
67,LP001233,Male,Yes,1.0,Graduate,No,10750,0.000000,312.00000,360.000000,1.0,Urban,Y
68,LP001238,Male,Yes,4.0,Not Graduate,Yes,7100,0.000000,125.00000,60.000000,1.0,Urban,Y
69,LP001241,Female,No,0.0,Graduate,No,4300,0.000000,136.00000,360.000000,0.0,Semiurban,N
70,LP001243,Male,Yes,0.0,Graduate,No,3208,3066.000000,172.00000,360.000000,1.0,Urban,Y
71,LP001245,Male,Yes,2.0,Not Graduate,Yes,1875,1875.000000,97.00000,360.000000,1.0,Semiurban,Y
72,LP001248,Male,No,0.0,Graduate,No,3500,0.000000,81.00000,300.000000,1.0,Semiurban,Y
73,LP001250,Male,Yes,4.0,Not Graduate,No,4755,0.000000,95.00000,342.201873,0.0,Semiurban,N
74,LP001253,Male,Yes,4.0,Graduate,Yes,5266,1774.000000,187.00000,360.000000,1.0,Semiurban,Y
75,LP001255,Male,No,0.0,Graduate,No,3750,0.000000,113.00000,480.000000,1.0,Urban,N
76,LP001256,Male,No,0.0,Graduate,No,3750,4750.000000,176.00000,360.000000,1.0,Urban,N
77,LP001259,Male,Yes,1.0,Graduate,Yes,1000,3022.000000,110.00000,360.000000,1.0,Urban,N
78,LP001263,Male,Yes,4.0,Graduate,No,3167,4000.000000,180.00000,300.000000,0.0,Semiurban,N
79,LP001264,Male,Yes,3.0,Not Graduate,Yes,3333,2166.000000,130.00000,360.000000,1.0,Semiurban,Y
80,LP001265,Female,No,0.0,Graduate,No,3846,0.000000,111.00000,360.000000,1.0,Semiurban,Y
81,LP001266,Male,Yes,1.0,Graduate,Yes,2395,0.000000,142.51153,360.000000,1.0,Semiurban,Y
82,LP001267,Female,Yes,2.0,Graduate,No,1378,1881.000000,167.00000,360.000000,1.0,Urban,N
83,LP001273,Male,Yes,0.0,Graduate,No,6000,2250.000000,265.00000,360.000000,1.0,Semiurban,N
84,LP001275,Male,Yes,1.0,Graduate,No,3988,0.000000,50.00000,240.000000,1.0,Urban,Y
85,LP001279,Male,No,0.0,Graduate,No,2366,2531.000000,136.00000,360.000000,1.0,Semiurban,Y
86,LP001280,Male,Yes,2.0,Not Graduate,No,3333,2000.000000,99.00000,360.000000,1.0,Semiurban,Y
87,LP001282,Male,Yes,0.0,Graduate,No,2500,2118.000000,104.00000,360.000000,1.0,Semiurban,Y
88,LP001289,Male,No,0.0,Graduate,No,8566,0.000000,210.00000,360.000000,1.0,Urban,Y
89,LP001310,Male,Yes,0.0,Graduate,No,5695,4167.000000,175.00000,360.000000,1.0,Semiurban,Y
90,LP001316,Male,Yes,0.0,Graduate,No,2958,2900.000000,131.00000,360.000000,1.0,Semiurban,Y
91,LP001318,Male,Yes,2.0,Graduate,No,6250,5654.000000,188.00000,180.000000,1.0,Semiurban,Y
92,LP001319,Male,Yes,2.0,Not Graduate,No,3273,1820.000000,81.00000,360.000000,1.0,Urban,Y
93,LP001322,Male,No,0.0,Graduate,No,4133,0.000000,122.00000,360.000000,1.0,Semiurban,Y
94,LP001325,Male,No,0.0,Not Graduate,No,3620,0.000000,25.00000,120.000000,1.0,Semiurban,Y
95,LP001326,Male,No,0.0,Graduate,Yes,6782,0.000000,142.51153,360.000000,1.0,Urban,N
96,LP001327,Female,Yes,0.0,Graduate,No,2484,2302.000000,137.00000,360.000000,1.0,Semiurban,Y
97,LP001333,Male,Yes,0.0,Graduate,No,1977,997.000000,50.00000,360.000000,1.0,Semiurban,Y
98,LP001334,Male,Yes,0.0,Not Graduate,No,4188,0.000000,115.00000,180.000000,1.0,Semiurban,Y
99,LP001343,Male,Yes,0.0,Graduate,No,1759,3541.000000,131.00000,360.000000,1.0,Semiurban,Y
100,LP001345,Male,Yes,2.0,Not Graduate,No,4288,3263.000000,133.00000,180.000000,1.0,Urban,Y
101,LP001349,Male,No,0.0,Graduate,No,4843,3806.000000,151.00000,360.000000,1.0,Semiurban,Y
102,LP001350,Male,Yes,0.0,Graduate,No,13650,0.000000,142.51153,360.000000,1.0,Urban,Y
103,LP001356,Male,Yes,0.0,Graduate,No,4652,3583.000000,142.51153,360.000000,1.0,Semiurban,Y
104,LP001357,Male,No,0.0,Graduate,No,3816,754.000000,160.00000,360.000000,1.0,Urban,Y
105,LP001367,Male,Yes,1.0,Graduate,No,3052,1030.000000,100.00000,360.000000,1.0,Urban,Y
106,LP001369,Male,Yes,2.0,Graduate,No,11417,1126.000000,225.00000,360.000000,1.0,Urban,Y
107,LP001370,Male,No,0.0,Not Graduate,Yes,7333,0.000000,120.00000,360.000000,1.0,Rural,N
108,LP001379,Male,Yes,2.0,Graduate,No,3800,3600.000000,216.00000,360.000000,0.0,Urban,N
109,LP001384,Male,Yes,4.0,Not Graduate,No,2071,754.000000,94.00000,480.000000,1.0,Semiurban,Y
110,LP001385,Male,No,0.0,Graduate,No,5316,0.000000,136.00000,360.000000,1.0,Urban,Y
111,LP001387,Female,Yes,0.0,Graduate,Yes,2929,2333.000000,139.00000,360.000000,1.0,Semiurban,Y
112,LP001391,Male,Yes,0.0,Not Graduate,No,3572,4114.000000,152.00000,342.201873,0.0,Rural,N
113,LP001392,Female,No,1.0,Graduate,Yes,7451,0.000000,142.51153,360.000000,1.0,Semiurban,Y
114,LP001398,Male,No,0.0,Graduate,Yes,5050,0.000000,118.00000,360.000000,1.0,Semiurban,Y
115,LP001401,Male,Yes,1.0,Graduate,No,14583,0.000000,185.00000,180.000000,1.0,Rural,Y
116,LP001404,Female,Yes,0.0,Graduate,No,3167,2283.000000,154.00000,360.000000,1.0,Semiurban,Y
117,LP001405,Male,Yes,1.0,Graduate,No,2214,1398.000000,85.00000,360.000000,1.0,Urban,Y
118,LP001421,Male,Yes,0.0,Graduate,No,5568,2142.000000,175.00000,360.000000,1.0,Rural,N
119,LP001422,Female,No,0.0,Graduate,No,10408,0.000000,259.00000,360.000000,1.0,Urban,Y
120,LP001426,Male,Yes,0.0,Graduate,No,5667,2667.000000,180.00000,360.000000,1.0,Rural,Y
121,LP001430,Female,No,0.0,Graduate,No,4166,0.000000,44.00000,360.000000,1.0,Semiurban,Y
122,LP001431,Female,No,0.0,Graduate,No,2137,8980.000000,137.00000,360.000000,0.0,Semiurban,Y
123,LP001432,Male,Yes,2.0,Graduate,No,2957,0.000000,81.00000,360.000000,1.0,Semiurban,Y
124,LP001439,Male,Yes,0.0,Not Graduate,No,4300,2014.000000,194.00000,360.000000,1.0,Rural,Y
125,LP001443,Female,No,0.0,Graduate,No,3692,0.000000,93.00000,360.000000,1.0,Rural,Y
126,LP001448,Male,Yes,4.0,Graduate,No,23803,0.000000,370.00000,360.000000,1.0,Rural,Y
127,LP001449,Male,No,0.0,Graduate,No,3865,1640.000000,142.51153,360.000000,1.0,Rural,Y
128,LP001451,Male,Yes,1.0,Graduate,Yes,10513,3850.000000,160.00000,180.000000,0.0,Urban,N
129,LP001465,Male,Yes,0.0,Graduate,No,6080,2569.000000,182.00000,360.000000,1.0,Rural,N
130,LP001469,Male,No,0.0,Graduate,Yes,20166,0.000000,650.00000,480.000000,1.0,Urban,Y
131,LP001473,Male,No,0.0,Graduate,No,2014,1929.000000,74.00000,360.000000,1.0,Urban,Y
132,LP001478,Male,No,0.0,Graduate,No,2718,0.000000,70.00000,360.000000,1.0,Semiurban,Y
133,LP001482,Male,Yes,0.0,Graduate,Yes,3459,0.000000,25.00000,120.000000,1.0,Semiurban,Y
134,LP001487,Male,No,0.0,Graduate,No,4895,0.000000,102.00000,360.000000,1.0,Semiurban,Y
135,LP001488,Male,Yes,4.0,Graduate,No,4000,7750.000000,290.00000,360.000000,1.0,Semiurban,N
136,LP001489,Female,Yes,0.0,Graduate,No,4583,0.000000,84.00000,360.000000,1.0,Rural,N
137,LP001491,Male,Yes,2.0,Graduate,Yes,3316,3500.000000,88.00000,360.000000,1.0,Urban,Y
138,LP001492,Male,No,0.0,Graduate,No,14999,0.000000,242.00000,360.000000,0.0,Semiurban,N
139,LP001493,Male,Yes,2.0,Not Graduate,No,4200,1430.000000,129.00000,360.000000,1.0,Rural,N
140,LP001497,Male,Yes,2.0,Graduate,No,5042,2083.000000,185.00000,360.000000,1.0,Rural,N
141,LP001498,Male,No,0.0,Graduate,No,5417,0.000000,168.00000,360.000000,1.0,Urban,Y
142,LP001504,Male,No,0.0,Graduate,Yes,6950,0.000000,175.00000,180.000000,1.0,Semiurban,Y
143,LP001507,Male,Yes,0.0,Graduate,No,2698,2034.000000,122.00000,360.000000,1.0,Semiurban,Y
144,LP001508,Male,Yes,2.0,Graduate,No,11757,0.000000,187.00000,180.000000,1.0,Urban,Y
145,LP001514,Female,Yes,0.0,Graduate,No,2330,4486.000000,100.00000,360.000000,1.0,Semiurban,Y
146,LP001516,Female,Yes,2.0,Graduate,No,14866,0.000000,70.00000,360.000000,1.0,Urban,Y
147,LP001518,Male,Yes,1.0,Graduate,No,1538,1425.000000,30.00000,360.000000,1.0,Urban,Y
148,LP001519,Female,No,0.0,Graduate,No,10000,1666.000000,225.00000,360.000000,1.0,Rural,N
149,LP001520,Male,Yes,0.0,Graduate,No,4860,830.000000,125.00000,360.000000,1.0,Semiurban,Y
150,LP001528,Male,No,0.0,Graduate,No,6277,0.000000,118.00000,360.000000,0.0,Rural,N
151,LP001529,Male,Yes,0.0,Graduate,Yes,2577,3750.000000,152.00000,360.000000,1.0,Rural,Y
152,LP001531,Male,No,0.0,Graduate,No,9166,0.000000,244.00000,360.000000,1.0,Urban,N
153,LP001532,Male,Yes,2.0,Not Graduate,No,2281,0.000000,113.00000,360.000000,1.0,Rural,N
154,LP001535,Male,No,0.0,Graduate,No,3254,0.000000,50.00000,360.000000,1.0,Urban,Y
155,LP001536,Male,Yes,4.0,Graduate,No,39999,0.000000,600.00000,180.000000,0.0,Semiurban,Y
156,LP001541,Male,Yes,1.0,Graduate,No,6000,0.000000,160.00000,360.000000,1.0,Rural,Y
157,LP001543,Male,Yes,1.0,Graduate,No,9538,0.000000,187.00000,360.000000,1.0,Urban,Y
158,LP001546,Male,No,0.0,Graduate,Yes,2980,2083.000000,120.00000,360.000000,1.0,Rural,Y
159,LP001552,Male,Yes,0.0,Graduate,No,4583,5625.000000,255.00000,360.000000,1.0,Semiurban,Y
160,LP001560,Male,Yes,0.0,Not Graduate,No,1863,1041.000000,98.00000,360.000000,1.0,Semiurban,Y
161,LP001562,Male,Yes,0.0,Graduate,No,7933,0.000000,275.00000,360.000000,1.0,Urban,N
162,LP001565,Male,Yes,1.0,Graduate,No,3089,1280.000000,121.00000,360.000000,0.0,Semiurban,N
163,LP001570,Male,Yes,2.0,Graduate,No,4167,1447.000000,158.00000,360.000000,1.0,Rural,Y
164,LP001572,Male,Yes,0.0,Graduate,No,9323,0.000000,75.00000,180.000000,1.0,Urban,Y
165,LP001574,Male,Yes,0.0,Graduate,No,3707,3166.000000,182.00000,342.201873,1.0,Rural,Y
166,LP001577,Female,Yes,0.0,Graduate,No,4583,0.000000,112.00000,360.000000,1.0,Rural,N
167,LP001578,Male,Yes,0.0,Graduate,No,2439,3333.000000,129.00000,360.000000,1.0,Rural,Y
168,LP001579,Male,No,0.0,Graduate,No,2237,0.000000,63.00000,480.000000,0.0,Semiurban,N
169,LP001580,Male,Yes,2.0,Graduate,No,8000,0.000000,200.00000,360.000000,1.0,Semiurban,Y
170,LP001581,Male,Yes,0.0,Not Graduate,Yes,1820,1769.000000,95.00000,360.000000,1.0,Rural,Y
171,LP001585,Male,Yes,4.0,Graduate,No,51763,0.000000,700.00000,300.000000,1.0,Urban,Y
172,LP001586,Male,Yes,4.0,Not Graduate,No,3522,0.000000,81.00000,180.000000,1.0,Rural,N
173,LP001594,Male,Yes,0.0,Graduate,No,5708,5625.000000,187.00000,360.000000,1.0,Semiurban,Y
174,LP001603,Male,Yes,0.0,Not Graduate,Yes,4344,736.000000,87.00000,360.000000,1.0,Semiurban,N
175,LP001606,Male,Yes,0.0,Graduate,No,3497,1964.000000,116.00000,360.000000,1.0,Rural,Y
176,LP001608,Male,Yes,2.0,Graduate,No,2045,1619.000000,101.00000,360.000000,1.0,Rural,Y
177,LP001610,Male,Yes,4.0,Graduate,No,5516,11300.000000,495.00000,360.000000,0.0,Semiurban,N
178,LP001616,Male,Yes,1.0,Graduate,No,3750,0.000000,116.00000,360.000000,1.0,Semiurban,Y
179,LP001630,Male,No,0.0,Not Graduate,No,2333,1451.000000,102.00000,480.000000,0.0,Urban,N
180,LP001633,Male,Yes,1.0,Graduate,No,6400,7250.000000,180.00000,360.000000,0.0,Urban,N
181,LP001634,Male,No,0.0,Graduate,No,1916,5063.000000,67.00000,360.000000,1.0,Rural,N
182,LP001636,Male,Yes,0.0,Graduate,No,4600,0.000000,73.00000,180.000000,1.0,Semiurban,Y
183,LP001637,Male,Yes,1.0,Graduate,No,33846,0.000000,260.00000,360.000000,1.0,Semiurban,N
184,LP001639,Female,Yes,0.0,Graduate,No,3625,0.000000,108.00000,360.000000,1.0,Semiurban,Y
185,LP001640,Male,Yes,0.0,Graduate,Yes,39147,4750.000000,120.00000,360.000000,1.0,Semiurban,Y
186,LP001641,Male,Yes,1.0,Graduate,Yes,2178,0.000000,66.00000,300.000000,0.0,Rural,N
187,LP001643,Male,Yes,0.0,Graduate,No,2383,2138.000000,58.00000,360.000000,1.0,Rural,Y
188,LP001644,Male,Yes,0.0,Graduate,Yes,674,5296.000000,168.00000,360.000000,1.0,Rural,Y
189,LP001647,Male,Yes,0.0,Graduate,No,9328,0.000000,188.00000,180.000000,1.0,Rural,Y
190,LP001653,Male,No,0.0,Not Graduate,No,4885,0.000000,48.00000,360.000000,1.0,Rural,Y
191,LP001656,Male,No,0.0,Graduate,No,12000,0.000000,164.00000,360.000000,1.0,Semiurban,N
192,LP001657,Male,Yes,0.0,Not Graduate,No,6033,0.000000,160.00000,360.000000,1.0,Urban,N
193,LP001658,Male,No,0.0,Graduate,No,3858,0.000000,76.00000,360.000000,1.0,Semiurban,Y
194,LP001664,Male,No,0.0,Graduate,No,4191,0.000000,120.00000,360.000000,1.0,Rural,Y
195,LP001665,Male,Yes,1.0,Graduate,No,3125,2583.000000,170.00000,360.000000,1.0,Semiurban,N
196,LP001666,Male,No,0.0,Graduate,No,8333,3750.000000,187.00000,360.000000,1.0,Rural,Y
197,LP001669,Female,No,0.0,Not Graduate,No,1907,2365.000000,120.00000,342.201873,1.0,Urban,Y
198,LP001671,Female,Yes,0.0,Graduate,No,3416,2816.000000,113.00000,360.000000,1.0,Semiurban,Y
199,LP001673,Male,No,0.0,Graduate,Yes,11000,0.000000,83.00000,360.000000,1.0,Urban,N
200,LP001674,Male,Yes,1.0,Not Graduate,No,2600,2500.000000,90.00000,360.000000,1.0,Semiurban,Y
201,LP001677,Male,No,2.0,Graduate,No,4923,0.000000,166.00000,360.000000,0.0,Semiurban,Y
202,LP001682,Male,Yes,4.0,Not Graduate,No,3992,0.000000,142.51153,180.000000,1.0,Urban,N
203,LP001688,Male,Yes,1.0,Not Graduate,No,3500,1083.000000,135.00000,360.000000,1.0,Urban,Y
204,LP001691,Male,Yes,2.0,Not Graduate,No,3917,0.000000,124.00000,360.000000,1.0,Semiurban,Y
205,LP001692,Female,No,0.0,Not Graduate,No,4408,0.000000,120.00000,360.000000,1.0,Semiurban,Y
206,LP001693,Female,No,0.0,Graduate,No,3244,0.000000,80.00000,360.000000,1.0,Urban,Y
207,LP001698,Male,No,0.0,Not Graduate,No,3975,2531.000000,55.00000,360.000000,1.0,Rural,Y
208,LP001699,Male,No,0.0,Graduate,No,2479,0.000000,59.00000,360.000000,1.0,Urban,Y
209,LP001702,Male,No,0.0,Graduate,No,3418,0.000000,127.00000,360.000000,1.0,Semiurban,N
210,LP001708,Female,No,0.0,Graduate,No,10000,0.000000,214.00000,360.000000,1.0,Semiurban,N
211,LP001711,Male,Yes,4.0,Graduate,No,3430,1250.000000,128.00000,360.000000,0.0,Semiurban,N
212,LP001713,Male,Yes,1.0,Graduate,Yes,7787,0.000000,240.00000,360.000000,1.0,Urban,Y
213,LP001715,Male,Yes,4.0,Not Graduate,Yes,5703,0.000000,130.00000,360.000000,1.0,Rural,Y
214,LP001716,Male,Yes,0.0,Graduate,No,3173,3021.000000,137.00000,360.000000,1.0,Urban,Y
215,LP001720,Male,Yes,4.0,Not Graduate,No,3850,983.000000,100.00000,360.000000,1.0,Semiurban,Y
216,LP001722,Male,Yes,0.0,Graduate,No,150,1800.000000,135.00000,360.000000,1.0,Rural,N
217,LP001726,Male,Yes,0.0,Graduate,No,3727,1775.000000,131.00000,360.000000,1.0,Semiurban,Y
218,LP001732,Male,Yes,2.0,Graduate,Yes,5000,0.000000,72.00000,360.000000,0.0,Semiurban,N
219,LP001734,Female,Yes,2.0,Graduate,No,4283,2383.000000,127.00000,360.000000,1.0,Semiurban,Y
220,LP001736,Male,Yes,0.0,Graduate,No,2221,0.000000,60.00000,360.000000,0.0,Urban,N
221,LP001743,Male,Yes,2.0,Graduate,No,4009,1717.000000,116.00000,360.000000,1.0,Semiurban,Y
222,LP001744,Male,No,0.0,Graduate,No,2971,2791.000000,144.00000,360.000000,1.0,Semiurban,Y

 # replace Function

In [69]:
cr.Gender = cr.Gender.replace({'Male':0, 'Female':1})

In [70]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,No,0.0,Graduate,No,5849,0.0,142.51153,360.0,1.0,Urban,Y
1,LP001003,0,Yes,1.0,Graduate,No,4583,1508.0,128.00000,360.0,1.0,Rural,N
2,LP001005,0,Yes,0.0,Graduate,Yes,3000,0.0,66.00000,360.0,1.0,Urban,Y
3,LP001006,0,Yes,0.0,Not Graduate,No,2583,2358.0,120.00000,360.0,1.0,Urban,Y
4,LP001008,0,No,0.0,Graduate,No,6000,0.0,141.00000,360.0,1.0,Urban,Y

In [71]:
cr.Married = cr.Married.replace({'Yes':1, 'No':0})

In [72]:
cr.Self_Employed = cr.Self_Employed.replace({'Yes':1, 'No':0})

In [73]:
cr.Property_Area = cr.Property_Area.replace({'Urban':1,'Rural':0})

In [74]:
cr.Loan_Status = cr.Loan_Status.replace({'Y':1,'N':0})

# Encoding Techiques

In [75]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [76]:
## Another Method to convert Non numeric to Numeric
# Techinique (One Hot Encoding) -->> Dummy Variable Categoriztion but over here the number of columns will Increase
# where 1  will indicate the presence and 0 will indicate absense

In [77]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [78]:
cr = cr.iloc[:,1::] # to remove Loan_id
cr.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [79]:
cr1 = pd.get_dummies(cr)

In [80]:
print(cr.shape)
print(cr1.shape)

(981, 12)
(981, 19)

In [81]:
cr1.head()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_N,Loan_Status_Y
0,0.0,5849,0.0,NaN,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1
1,1.0,4583,1508.0,128.0,360.0,1.0,0,1,0,1,1,0,1,0,1,0,0,1,0
2,0.0,3000,0.0,66.0,360.0,1.0,0,1,0,1,1,0,0,1,0,0,1,0,1
3,0.0,2583,2358.0,120.0,360.0,1.0,0,1,0,1,0,1,1,0,0,0,1,0,1
4,0.0,6000,0.0,141.0,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1

# lets see one more method in which we can convert non numeric to numeric using LabelEncoding

In [82]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [83]:
# sklearn

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
le = LabelEncoder() #Created Object of Label Encoder so that functions can get attached to it

In [86]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [88]:
cr.Gender = le.fit_transform(cr.Gender)

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['float', 'str']

In [89]:
cr.Married = le.fit_transform(cr.Married)

TypeError: Encoders require their input to be uniformly strings or numbers. Got ['float', 'str']

In [ ]:
cr.Education = le.fit_transform(cr.Education)

In [ ]:
cr.info()

In [ ]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [ ]:
cr.select_dtypes(include=['object']).columns

In [ ]:
cr[cr.select_dtypes(include=['object']).columns]

In [ ]:
# Now Aim is to convert Non Numeric into Numeric in a single line of code using Label Encoder

In [90]:
cr.Credit_History = cr.Credit_History.fillna(1)
cr.Gender = cr.Gender.fillna('Male')
cr.Married = cr.Married.fillna('No')
cr.Dependents = cr.Dependents.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna('Yes')
cr.LoanAmount = cr.LoanAmount.fillna(cr.LoanAmount.mean())
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())

In [91]:
cr = cr.iloc[:,1::]

In [92]:
cr.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [93]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [94]:
cr[cr.select_dtypes(include='object').columns] = cr[cr.select_dtypes(include='object').columns].apply(le.fit_transform)

In [95]:
#Cross Table

In [96]:
## PS: Is there any role of Education in Loan Approval or not

In [97]:
pd.crosstab(cr.Education, cr.Loan_Status)

Loan_Status    0    1
Education
0            196  567
1             73  145

In [98]:
pd.crosstab(cr.Gender, cr.Loan_Status)

Loan_Status    0    1
Gender
0             55  127
1            214  585

In [99]:
pd.crosstab(cr.Self_Employed, cr.Loan_Status)

Loan_Status      0    1
Self_Employed
0              220  587
1               49  125

In [100]:
# percentile Function

In [101]:
cr.ApplicantIncome.describe(percentiles=[.1,.2,.3,.4,.5,.6,.7,.8,.9,1])

count      981.000000
mean      5179.795107
std       5695.104533
min          0.000000
10%       2221.000000
20%       2609.000000
30%       3062.000000
40%       3413.000000
50%       3800.000000
60%       4301.000000
70%       5000.000000
80%       6080.000000
90%       8750.000000
100%     81000.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [102]:
# Co-relation Matrix ... range of Co-relation is (-1 to 1)

In [103]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [104]:
cr.corr().round(3)

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
Dependents,1.000,0.138,-0.003,0.150,-0.088,-0.058
ApplicantIncome,0.138,1.000,-0.114,0.552,-0.023,0.023
CoapplicantIncome,-0.003,-0.114,1.000,0.179,-0.044,-0.027
LoanAmount,0.150,0.552,0.179,1.000,0.056,-0.008
Loan_Amount_Term,-0.088,-0.023,-0.044,0.056,1.000,-0.020
Credit_History,-0.058,0.023,-0.027,-0.008,-0.020,1.000

In [105]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [106]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [107]:
c1 = cr[cr.ApplicantIncome >=4500]

In [108]:
c1.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,354.000000,364.000000,364.000000,351.000000,356.000000,342.000000
mean,1.076271,8807.038462,1141.662088,185.689459,344.123596,0.859649
std,1.345374,8087.767129,2198.969094,102.104976,59.364013,0.347860
min,0.000000,4500.000000,0.000000,26.000000,12.000000,0.000000
25%,0.000000,5183.000000,0.000000,125.000000,360.000000,1.000000
50%,1.000000,6280.000000,0.000000,158.000000,360.000000,1.000000
75%,2.000000,9167.000000,1651.000000,208.500000,360.000000,1.000000
max,4.000000,81000.000000,14507.000000,700.000000,480.000000,1.000000

In [109]:
#annother Way
#Using Query method

In [110]:
cr2.ApplicantIncome.describe()

AttributeError: 'DataFrame' object has no attribute 'ApplicantIncome'

In [111]:
cr2 = cr.query('ApplicantIncome > 4500')

In [112]:
cr3 = cr.query("Education == 'Graduate'")

In [113]:
cr3.Education.value_counts()

Graduate    763
Name: Education, dtype: int64

In [114]:
cr4 = cr.query(('Gender == "Male" & ApplicantIncome > 4000'))

In [115]:
cr4.Gender.value_counts()

Male    363
Name: Gender, dtype: int64

In [116]:
cr4.ApplicantIncome.describe()

count      363.000000
mean      7940.176309
std       7665.139159
min       4006.000000
25%       4746.000000
50%       5829.000000
75%       8076.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [117]:
# Create a dtframe which select all the numeric columns from this cr dataframe

In [118]:
cr5 = cr[cr.select_dtypes(include =['int','float']).columns]
cr5.head()

   Dependents  CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History
0         0.0                0.0         NaN             360.0             1.0
1         1.0             1508.0       128.0             360.0             1.0
2         0.0                0.0        66.0             360.0             1.0
3         0.0             2358.0       120.0             360.0             1.0
4         0.0                0.0       141.0             360.0             1.0

# Different ways of reading file

In [119]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv', usecols=['ApplicantIncome','Gender','LoanAmount'])

In [120]:
cr.head()

  Gender  ApplicantIncome  LoanAmount
0   Male             5849         NaN
1   Male             4583       128.0
2   Male             3000        66.0
3   Male             2583       120.0
4   Male             6000       141.0

# To read file without using read_csv .. read it using clipbaord

In [121]:
cr_clip = pd.read_clipboard()

In [122]:
cr_clip

,new_income,=,2*cr.ApplicantIncome,#,new_income.1,is,new,c
0,cr_new,=,"pd.concat([cr,","new_income],",axis,=,1),NaN
1,cr_new.head(),None,None,None,None,None,None,NaN

In [123]:
# sort Data in ascending or descending order
# PS i want to sort income in descending

In [124]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')

In [125]:
cr_sort = cr.sort_values('ApplicantIncome', ascending=True)

In [126]:
cr.sort_values('ApplicantIncome', ascending=False)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
409,LP002317,Male,Yes,4.0,Graduate,No,81000,0.000000,360.0,360.0,0.0,Rural,N
695,LP001428,Male,Yes,4.0,Graduate,No,72529,0.000000,360.0,360.0,1.0,Urban,Y
333,LP002101,Male,Yes,0.0,Graduate,NaN,63337,0.000000,490.0,180.0,1.0,Urban,Y
171,LP001585,NaN,Yes,4.0,Graduate,No,51763,0.000000,700.0,300.0,1.0,Urban,Y
155,LP001536,Male,Yes,4.0,Graduate,No,39999,0.000000,600.0,180.0,0.0,Semiurban,Y
185,LP001640,Male,Yes,0.0,Graduate,Yes,39147,4750.000000,120.0,360.0,1.0,Semiurban,Y
443,LP002422,Male,No,1.0,Graduate,No,37719,0.000000,152.0,360.0,1.0,Semiurban,Y
183,LP001637,Male,Yes,1.0,Graduate,No,33846,0.000000,260.0,360.0,1.0,Semiurban,N
757,LP001791,Male,Yes,0.0,Graduate,Yes,32000,0.000000,550.0,360.0,NaN,Semiurban,Y
893,LP002553,NaN,No,0.0,Graduate,No,29167,0.000000,185.0,360.0,1.0,Semiurban,Y
886,LP002485,Male,No,1.0,Graduate,No,24797,0.000000,240.0,360.0,1.0,Semiurban,Y
126,LP001448,NaN,Yes,4.0,Graduate,No,23803,0.000000,370.0,360.0,1.0,Rural,Y
506,LP002624,Male,Yes,0.0,Graduate,No,20833,6667.000000,480.0,360.0,NaN,Urban,Y
284,LP001922,Male,Yes,0.0,Graduate,No,20667,0.000000,NaN,360.0,1.0,Rural,N
308,LP001996,Male,No,0.0,Graduate,No,20233,0.000000,480.0,360.0,1.0,Rural,N
130,LP001469,Male,No,0.0,Graduate,Yes,20166,0.000000,650.0,480.0,NaN,Urban,Y
369,LP002191,Male,Yes,0.0,Graduate,No,19730,5266.000000,570.0,360.0,1.0,Rural,N
561,LP002813,Female,Yes,1.0,Graduate,Yes,19484,0.000000,600.0,360.0,1.0,Semiurban,Y
877,LP002433,Male,Yes,1.0,Graduate,No,18840,0.000000,234.0,360.0,1.0,Rural,Y
487,LP002547,Male,Yes,1.0,Graduate,No,18333,0.000000,500.0,360.0,1.0,Urban,N
534,LP002731,Female,No,0.0,Not Graduate,Yes,18165,0.000000,125.0,360.0,1.0,Urban,Y
525,LP002699,Male,Yes,2.0,Graduate,Yes,17500,0.000000,400.0,360.0,1.0,Rural,Y
493,LP002582,Female,No,0.0,Not Graduate,Yes,17263,0.000000,225.0,360.0,1.0,Semiurban,Y
467,LP002501,NaN,Yes,0.0,Graduate,No,16692,0.000000,110.0,360.0,1.0,Semiurban,Y
478,LP002531,Male,Yes,1.0,Graduate,Yes,16667,2250.000000,86.0,360.0,1.0,Semiurban,Y
572,LP002855,Male,Yes,2.0,Graduate,No,16666,0.000000,275.0,360.0,1.0,Urban,Y
475,LP002527,Male,Yes,2.0,Graduate,Yes,16525,1014.000000,150.0,360.0,1.0,Rural,Y
254,LP001844,Male,No,0.0,Graduate,Yes,16250,0.000000,192.0,360.0,0.0,Urban,N
594,LP002938,Male,Yes,0.0,Graduate,Yes,16120,0.000000,260.0,360.0,1.0,Urban,Y
937,LP002791,Male,No,1.0,Graduate,NaN,16000,5000.000000,40.0,360.0,1.0,Semiurban,Y
370,LP002194,Female,No,0.0,Graduate,Yes,15759,0.000000,55.0,360.0,1.0,Semiurban,Y
793,LP002017,Male,Yes,4.0,Graduate,No,15312,0.000000,187.0,360.0,NaN,Urban,Y
324,LP002065,Male,Yes,4.0,Graduate,No,15000,0.000000,300.0,360.0,1.0,Rural,Y
138,LP001492,Male,No,0.0,Graduate,No,14999,0.000000,242.0,360.0,0.0,Semiurban,N
916,LP002654,Female,No,NaN,Graduate,Yes,14987,0.000000,177.0,360.0,1.0,Rural,Y
844,LP002294,Male,No,0.0,Graduate,No,14911,14507.000000,130.0,360.0,1.0,Semiurban,Y
424,LP002364,Male,Yes,0.0,Graduate,No,14880,0.000000,96.0,360.0,1.0,Semiurban,Y
146,LP001516,Female,Yes,2.0,Graduate,No,14866,0.000000,70.0,360.0,1.0,Urban,Y
258,LP001859,Male,Yes,0.0,Graduate,No,14683,2100.000000,304.0,360.0,1.0,Rural,N
278,LP001907,Male,Yes,0.0,Graduate,No,14583,0.000000,436.0,360.0,1.0,Semiurban,Y
115,LP001401,Male,Yes,1.0,Graduate,No,14583,0.000000,185.0,180.0,1.0,Rural,Y
102,LP001350,Male,Yes,NaN,Graduate,No,13650,0.000000,NaN,360.0,1.0,Urban,Y
622,LP001059,Male,Yes,2.0,Graduate,NaN,13633,0.000000,280.0,240.0,1.0,Urban,Y
705,LP001483,Male,Yes,4.0,Graduate,No,13518,0.000000,390.0,360.0,1.0,Rural,Y
509,LP002634,Female,No,1.0,Graduate,No,13262,0.000000,40.0,360.0,1.0,Urban,Y
802,LP002057,Male,Yes,0.0,Not Graduate,No,13083,0.000000,NaN,360.0,1.0,Rural,Y
759,LP001797,Female,No,0.0,Graduate,No,12941,0.000000,150.0,300.0,1.0,Urban,Y
432,LP002386,Male,No,0.0,Graduate,NaN,12876,0.000000,405.0,360.0,1.0,Semiurban,Y
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.000000,349.0,360.0,1.0,Semiurban,N
34,LP001100,Male,No,4.0,Graduate,No,12500,3000.000000,320.0,360.0,1.0,Rural,N
738,LP001655,Female,No,0.0,Graduate,No,12500,0.000000,300.0,360.0,0.0,Urban,N
627,LP001094,Male,Yes,2.0,Graduate,NaN,12173,0.000000,166.0,360.0,0.0,Semiurban,N
604,LP002959,Female,Yes,1.0,Graduate,No,12000,0.000000,496.0,360.0,1.0,Semiurban,Y
191,LP001656,Male,No,0.0,Graduate,No,12000,0.000000,164.0,360.0,1.0,Semiurban,N
144,LP001508,Male,Yes,2.0,Graduate,No,11757,0.000000,187.0,180.0,1.0,Urban,Y
54,LP001186,Female,Yes,1.0,Graduate,Yes,11500,0.000000,286.0,360.0,0.0,Urban,N
106,LP001369,Male,Yes,2.0,Graduate,No,11417,1126.000000,225.0,360.0,1.0,Urban,Y
533,LP002729,Male,No,1.0,Graduate,No,11250,0.000000,196.0,360.0,NaN,Semiurban,N
271,LP001891,Male,Yes,0.0,Graduate,No,11146,0.000000,136.0,360.0,1.0,Urban,Y
199,LP001673,Male,No,0.0,Graduate,Yes,11000,0.000000,83.0,360.0,1.0,Urban,N
758,LP001794,Male,Yes,2.0,Graduate,Yes,10890,0.000000,260.0,12.0,1.0,Rural,Y
483,LP002541,Male,Yes,0.0,Graduate,No,10833,0.000000,234.0,360.0,1.0,Semiurban,Y
67,LP001233,Male,Yes,1.0,Graduate,No,10750,0.000000,312.0,360.0,1.0,Urban,Y
128,LP001451,Male,Yes,1.0,Graduate,Yes,10513,3850.000000,160.0,180.0,0.0,Urban,N
438,LP002403,Male,No,0.0,Graduate,Yes,10416,0.000000,187.0,360.0,0.0,Urban,N
119,LP001422,Female,No,0.0,Graduate,No,10408,0.000000,259.0,360.0,1.0,Urban,Y
798,LP002045,Male,Yes,4.0,Graduate,No,10166,750.000000,150.0,NaN,1.0,Urban,Y
557,LP002795,Male,Yes,4.0,Graduate,Yes,10139,0.000000,260.0,360.0,1.0,Semiurban,Y
435,LP002393,Female,NaN,NaN,Graduate,No,10047,0.000000,NaN,240.0,1.0,Semiurban,Y
148,LP001519,Female,No,0.0,Graduate,No,10000,1666.000000,225.0,360.0,1.0,Rural,N
898,LP002570,Female,Yes,2.0,Graduate,No,10000,11666.000000,460.0,360.0,1.0,Urban,Y
861,LP002360,Male,Yes,NaN,Graduate,No,10000,0.000000,NaN,360.0,1.0,Urban,Y
210,LP001708,Female,No,0.0,Graduate,No,10000,0.000000,214.0,360.0,1.0,Semiurban,N
808,LP002077,Male,Yes,1.0,Graduate,No,10000,2690.000000,412.0,360.0,1.0,Semiurban,N
319,LP002050,Male,Yes,1.0,Graduate,Yes,10000,0.000000,155.0,360.0,1.0,Rural,N
598,LP002945,Male,Yes,0.0,Graduate,Yes,9963,0.000000,180.0,360.0,1.0,Rural,Y
334,LP002103,NaN,Yes,1.0,Graduate,Yes,9833,1833.000000,182.0,180.0,1.0,Urban,Y
712,LP001517,Male,Yes,4.0,Graduate,No,9719,0.000000,61.0,360.0,1.0,Urban,Y
246,LP001814,Male,Yes,2.0,Graduate,No,9703,0.000000,112.0,360.0,1.0,Urban,Y
945,LP002825,Male,Yes,4.0,Graduate,No,9699,0.000000,300.0,360.0,1.0,Urban,Y
25,LP001066,Male,Yes,0.0,Graduate,Yes,9560,0.000000,191.0,360.0,1.0,Semiurban,Y
157,LP001543,Male,Yes,1.0,Graduate,No,9538,0.000000,187.0,360.0,1.0,Urban,Y
289,LP001935,Male,No,0.0,Graduate,No,9508,0.000000,187.0,360.0,1.0,Rural,Y
391,LP002262,Male,Yes,4.0,Graduate,No,9504,0.000000,275.0,360.0,1.0,Rural,Y
592,LP002933,NaN,No,4.0,Graduate,Yes,9357,0.000000,292.0,360.0,1.0,Semiurban,Y
189,LP001647,Male,Yes,0.0,Graduate,No,9328,0.000000,188.0,180.0,1.0,Rural,Y
372,LP002201,Male,Yes,2.0,Graduate,Yes,9323,7873.000000,380.0,300.0,1.0,Rural,Y
164,LP001572,Male,Yes,0.0,Graduate,No,9323,0.000000,75.0,180.0,1.0,Urban,Y
632,LP001108,Male,Yes,0.0,Graduate,No,9226,7916.000000,300.0,360.0,1.0,Urban,Y
980,LP002989,Male,No,0.0,Graduate,Yes,9200,0.000000,98.0,180.0,1.0,Rural,Y
801,LP002056,Male,Yes,2.0,Graduate,No,9167,0.000000,235.0,360.0,1.0,Semiurban,Y
390,LP002255,Male,No,4.0,Graduate,No,9167,0.000000,185.0,360.0,1.0,Rural,Y
152,LP001531,Male,No,0.0,Graduate,No,9166,0.000000,244.0,360.0,1.0,Urban,N
350,LP002139,Male,Yes,0.0,Graduate,No,9083,0.000000,228.0,360.0,1.0,Semiurban,Y
897,LP002568,Male,No,0.0,Not Graduate,No,9000,0.000000,122.0,360.0,1.0,Rural,Y
564,LP002832,Male,Yes,2.0,Graduate,No,8799,0.000000,258.0,360.0,0.0,Urban,N
899,LP002572,Male,Yes,1.0,Graduate,NaN,8750,0.000000,297.0,360.0,1.0,Urban,Y
351,LP002140,Male,No,0.0,Graduate,No,8750,4167.000000,308.0,360.0,1.0,Rural,N
376,LP002219,Male,Yes,4.0,Graduate,No,8750,4996.000000,130.0,360.0,1.0,Rural,Y
814,LP002105,Male,Yes,0.0,Graduate,Yes,8706,0.000000,108.0,480.0,1.0,Rural,Y
761,LP001817,Male,No,0.0,Not Graduate,Yes,8703,0.000000,199.0,360.0,0.0,Rural,N
964,LP002899,Male,Yes,2.0,Graduate,No,8667,0.000000,254.0,360.0,1.0,Rural,Y
325,LP002067,Male,Yes,1.0,Graduate,Yes,8666,4983.000000,376.0,360.0,0.0,Rural,N
430,LP002377,Female,No,1.0,Graduate,Yes,8624,0.000000,150.0,360.0,1.0,Semiurban,Y
88,LP001289,Male,No,0.0,Graduate,No,8566,0.000000,210.0,360.0,1.0,Urban,Y
974,LP002965,Female,Yes,0.0,Graduate,No,8550,4255.000000,96.0,360.0,NaN,Urban,Y
697,LP001446,Male,Yes,0.0,Graduate,No,8449,0.000000,257.0,360.0,1.0,Rural,N
959,LP002878,Male,Yes,4.0,Graduate,No,8334,0.000000,260.0,360.0,1.0,Urban,Y
459,LP002473,Male,Yes,0.0,Graduate,No,8334,0.000000,160.0,360.0,1.0,Semiurban,N
233,LP001776,Female,No,0.0,Graduate,No,8333,0.000000,280.0,360.0,1.0,Semiurban,Y
196,LP001666,Male,No,0.0,Graduate,No,8333,3750.000000,187.0,360.0,1.0,Rural,Y
356,LP002149,Male,Yes,2.0,Graduate,No,8333,3167.000000,165.0,360.0,1.0,Rural,Y
484,LP002543,Male,Yes,2.0,Graduate,No,8333,0.000000,246.0,360.0,1.0,Semiurban,Y
903,LP002593,Male,Yes,1.0,Graduate,No,8333,4000.000000,NaN,360.0,1.0,Urban,Y
408,LP002315,Male,Yes,1.0,Graduate,No,8300,0.000000,152.0,300.0,0.0,Semiurban,N
58,LP001198,Male,Yes,1.0,Graduate,No,8080,2250.000000,180.0,360.0,1.0,Urban,Y
611,LP002983,Male,Yes,1.0,Graduate,No,8072,240.000000,253.0,360.0,1.0,Urban,Y
169,LP001580,Male,Yes,2.0,Graduate,No,8000,0.000000,200.0,360.0,1.0,Semiurban,Y
663,LP001270,Male,Yes,4.0,Not Graduate,Yes,8000,250.000000,187.0,360.0,1.0,Semiurban,Y
693,LP001419,Female,Yes,0.0,Graduate,No,7950,0.000000,185.0,360.0,1.0,Urban,Y
523,LP002693,Male,Yes,2.0,Graduate,Yes,7948,7166.000000,480.0,360.0,1.0,Rural,Y
161,LP001562,Male,Yes,0.0,Graduate,No,7933,0.000000,275.0,360.0,1.0,Urban,N
441,LP002409,Male,Yes,0.0,Graduate,No,7901,1833.000000,180.0,360.0,1.0,Rural,Y
773,LP001881,Male,Yes,0.0,Not Graduate,No,7895,0.000000,143.0,360.0,1.0,Rural,N
803,LP002059,Male,Yes,2.0,Graduate,No,7874,3967.000000,336.0,360.0,1.0,Rural,Y
929,LP002766,Female,Yes,0.0,Graduate,No,7859,879.000000,165.0,180.0,1.0,Semiurban,Y
831,LP002192,Male,Yes,0.0,Graduate,No,7830,2183.000000,212.0,360.0,1.0,Rural,Y
212,LP001713,Male,Yes,1.0,Graduate,Yes,7787,0.000000,240.0,360.0,1.0,Urban,Y
461,LP002484,Male,Yes,4.0,Graduate,No,7740,0.000000,128.0,180.0,1.0,Urban,Y
309,LP001998,Male,Yes,2.0,Not Graduate,No,7667,0.000000,185.0,360.0,NaN,Rural,Y
682,LP001359,Male,Yes,0.0,Graduate,No,7666,0.000000,187.0,360.0,1.0,Semiurban,Y
20,LP001043,Male,Yes,0.0,Not Graduate,No,7660,0.000000,104.0,360.0,0.0,Urban,N
969,LP002932,Male,Yes,4.0,Graduate,No,7603,1213.000000,197.0,360.0,1.0,Urban,Y
847,LP002310,Female,No,1.0,Graduate,No,7600,0.000000,92.0,360.0,1.0,Semiurban,Y
612,LP002984,Male,Yes,2.0,Graduate,No,7583,0.000000,187.0,360.0,1.0,Urban,Y
223,LP001749,Male,Yes,0.0,Graduate,No,7578,1010.000000,175.0,NaN,1.0,Semiurban,Y
920,LP002721,Male,Yes,2.0,Graduate,Yes,7500,0.000000,183.0,360.0,1.0,Rural,Y
741,LP001663,Male,Yes,2.0,Graduate,No,7500,0.000000,225.0,360.0,1.0,Urban,Y
641,LP001169,Male,Yes,0.0,Graduate,No,7500,3750.000000,275.0,360.0,1.0,Urban,Y
914,LP002644,Male,Yes,1.0,Graduate,Yes,7500,0.000000,75.0,360.0,1.0,Urban,Y
113,LP001392,Female,No,1.0,Graduate,Yes,7451,0.000000,NaN,360.0,1.0,Semiurban,Y
404,LP002301,Female,No,0.0,Graduate,Yes,7441,0.000000,194.0,360.0,1.0,Rural,N
650,LP001208,Male,Yes,2.0,Graduate,NaN,7350,4029.000000,185.0,180.0,1.0,Urban,Y
444,LP002424,Male,Yes,0.0,Graduate,No,7333,8333.000000,175.0,300.0,NaN,Rural,Y
107,LP001370,Male,No,0.0,Not Graduate,NaN,7333,0.000000,120.0,360.0,1.0,Rural,N
423,LP002362,Male,Yes,1.0,Graduate,No,7250,1667.000000,110.0,NaN,0.0,Urban,N
263,LP001871,Female,No,0.0,Graduate,No,7200,0.000000,120.0,360.0,1.0,Rural,Y
383,LP002234,Male,No,0.0,Graduate,Yes,7167,0.000000,128.0,360.0,1.0,Urban,Y
439,LP002407,Female,Yes,0.0,Not Graduate,Yes,7142,0.000000,138.0,360.0,1.0,Rural,Y
68,LP001238,Male,Yes,4.0,Not Graduate,Yes,7100,0.000000,125.0,60.0,1.0,Urban,Y
454,LP002453,Male,No,0.0,Graduate,Yes,7085,0.000000,84.0,360.0,1.0,Semiurban,Y
675,LP001335,Male,Yes,0.0,Graduate,Yes,7016,292.000000,125.0,360.0,1.0,Urban,Y
942,LP002806,Male,Yes,4.0,Graduate,Yes,6958,1411.000000,150.0,360.0,1.0,Rural,Y
142,LP001504,Male,No,0.0,Graduate,Yes,6950,0.000000,175.0,180.0,1.0,Semiurban,Y
296,LP001953,Male,Yes,1.0,Graduate,No,6875,0.000000,200.0,360.0,1.0,Semiurban,Y
958,LP002876,Male,No,0.0,Graduate,No,6858,0.000000,176.0,360.0,1.0,Rural,Y
713,LP001527,Male,Yes,4.0,Graduate,No,6835,0.000000,188.0,360.0,NaN,Semiurban,Y
922,LP002744,Male,Yes,1.0,Graduate,No,6825,0.000000,162.0,360.0,1.0,Rural,Y
364,LP002180,Male,No,0.0,Graduate,Yes,6822,0.000000,141.0,360.0,1.0,Rural,Y
756,LP001789,Male,Yes,4.0,Not Graduate,NaN,6794,528.000000,139.0,360.0,0.0,Urban,N
662,LP001268,Male,No,0.0,Graduate,No,6792,3338.000000,187.0,NaN,1.0,Urban,Y
529,LP002716,Male,No,0.0,Not Graduate,No,6783,0.000000,130.0,360.0,1.0,Semiurban,Y
95,LP001326,Male,No,0.0,Graduate,NaN,6782,0.000000,NaN,360.0,NaN,Urban,N
476,LP002529,Male,Yes,2.0,Graduate,No,6700,1750.000000,230.0,300.0,1.0,Semiurban,Y
550,LP002778,Male,Yes,2.0,Graduate,Yes,6633,0.000000,NaN,360.0,0.0,Rural,N
247,LP001819,Male,Yes,1.0,Not Graduate,No,6608,0.000000,137.0,180.0,1.0,Urban,Y
580,LP002892,Male,Yes,2.0,Graduate,No,6540,0.000000,205.0,360.0,1.0,Semiurban,Y
657,LP001230,Male,No,0.0,Graduate,No,6500,2600.000000,200.0,360.0,1.0,Semiurban,Y
890,LP002542,Male,Yes,0.0,Graduate,NaN,6500,0.000000,144.0,360.0,1.0,Urban,Y
740,LP001662,Male,No,0.0,Graduate,No,6500,0.000000,71.0,360.0,0.0,Urban,N
431,LP002379,Male,No,0.0,Graduate,No,6500,0.000000,105.0,360.0,0.0,Rural,N
910,LP002614,NaN,No,0.0,Graduate,No,6478,0.000000,108.0,360.0,1.0,Semiurban,Y
539,LP002740,Male,Yes,4.0,Graduate,No,6417,0.000000,157.0,180.0,1.0,Rural,Y
574,LP002863,Male,Yes,4.0,Graduate,No,6406,0.000000,150.0,360.0,1.0,Semiurban,N
180,LP001633,Male,Yes,1.0,Graduate,No,6400,7250.000000,180.0,360.0,0.0,Urban,N
229,LP001761,Male,No,0.0,Graduate,Yes,6400,0.000000,200.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2.0,Not Graduate,Yes,6383,1000.000000,187.0,360.0,1.0,Rural,N
691,LP001413,Male,No,0.0,Graduate,Yes,6356,0.000000,50.0,360.0,1.0,Rural,Y
348,LP002137,Male,Yes,0.0,Graduate,No,6333,4583.000000,259.0,360.0,NaN,Semiurban,Y
368,LP002190,Male,Yes,1.0,Graduate,No,6325,0.000000,175.0,360.0,1.0,Semiurban,Y
915,LP002651,Male,Yes,1.0,Graduate,NaN,6300,0.000000,125.0,360.0,0.0,Urban,N
499,LP002602,Male,No,0.0,Graduate,No,6283,4416.000000,209.0,360.0,0.0,Rural,N
150,LP001528,Male,No,0.0,Graduate,No,6277,0.000000,118.0,360.0,0.0,Rural,N
709,LP001499,Female,Yes,4.0,Graduate,No,6260,0.000000,110.0,360.0,1.0,Semiurban,Y
411,LP002319,Male,Yes,0.0,Graduate,NaN,6256,0.000000,160.0,360.0,NaN,Urban,Y
227,LP001758,Male,Yes,2.0,Graduate,No,6250,1695.000000,210.0,360.0,1.0,Semiurban,Y
243,LP001807,Male,Yes,2.0,Graduate,Yes,6250,1300.000000,108.0,360.0,1.0,Rural,Y
224,LP001750,Male,Yes,0.0,Graduate,No,6250,0.000000,128.0,360.0,1.0,Semiurban,Y
645,LP001183,Male,Yes,2.0,Graduate,No,6250,820.000000,192.0,360.0,1.0,Urban,Y
91,LP001318,Male,Yes,2.0,Graduate,No,6250,5654.000000,188.0,180.0,1.0,Semiurban,Y
365,LP002181,Male,No,0.0,Not Graduate,No,6216,0.000000,133.0,360.0,1.0,Rural,N
851,LP002325,Male,Yes,2.0,Not Graduate,No,6166,13983.000000,102.0,360.0,1.0,Rural,Y
536,LP002734,Male,Yes,0.0,Graduate,No,6133,3906.000000,324.0,360.0,1.0,Urban,Y
573,LP002862,Male,Yes,2.0,Not Graduate,No,6125,1625.000000,187.0,480.0,1.0,Semiurban,N
412,LP002328,Male,Yes,0.0,Not Graduate,No,6096,0.000000,218.0,360.0,0.0,Rural,N
260,LP001865,Male,Yes,1.0,Graduate,No,6083,4250.000000,330.0,360.0,NaN,Urban,Y
129,LP001465,Male,Yes,0.0,Graduate,No,6080,2569.000000,182.0,360.0,NaN,Rural,N
511,LP002640,Male,Yes,1.0,Graduate,No,6065,2004.000000,250.0,360.0,1.0,Semiurban,Y
245,LP001813,Male,No,0.0,Graduate,Yes,6050,4333.000000,120.0,180.0,1.0,Urban,N
256,LP001849,Male,No,0.0,Not Graduate,No,6045,0.000000,115.0,360.0,0.0,Rural,N
192,LP001657,Male,Yes,0.0,Not Graduate,No,6033,0.000000,160.0,360.0,1.0,Urban,N
4,LP001008,Male,No,0.0,Graduate,No,6000,0.000000,141.0,360.0,1.0,Urban,Y
382,LP002231,Female,No,0.0,Graduate,No,6000,0.000000,156.0,360.0,1.0,Urban,Y
156,LP001541,Male,Yes,1.0,Graduate,No,6000,0.000000,160.0,360.0,NaN,Rural,Y
465,LP002494,Male,No,0.0,Graduate,No,6000,0.000000,140.0,360.0,1.0,Rural,Y
591,LP002931,Male,Yes,2.0,Graduate,Yes,6000,0.000000,205.0,240.0,1.0,Semiurban,N
83,LP001273,Male,Yes,0.0,Graduate,No,6000,2250.000000,265.0,360.0,NaN,Semiurban,N
21,LP001046,Male,Yes,1.0,Graduate,No,5955,5625.000000,315.0,360.0,1.0,Urban,Y
381,LP002229,Male,No,0.0,Graduate,No,5941,4232.000000,296.0,360.0,1.0,Semiurban,Y
427,LP002368,Male,Yes,2.0,Graduate,No,5935,0.000000,133.0,360.0,1.0,Semiurban,Y
562,LP002820,Male,Yes,0.0,Graduate,No,5923,2054.000000,211.0,360.0,1.0,Rural,Y
763,LP001822,Male,No,0.0,Graduate,No,5900,0.000000,150.0,360.0,1.0,Urban,Y
0,LP001002,Male,No,0.0,Graduate,No,5849,0.000000,NaN,360.0,1.0,Urban,Y
652,LP001211,Male,No,0.0,Graduate,Yes,5833,0.000000,116.0,360.0,1.0,Urban,Y
809,LP002083,Male,No,0.0,Graduate,Yes,5833,0.000000,116.0,360.0,1.0,Urban,Y
882,LP002450,Male,Yes,2.0,Graduate,No,5833,750.000000,49.0,360.0,0.0,Rural,N
420,LP002348,Male,Yes,0.0,Graduate,No,5829,0.000000,138.0,360.0,1.0,Rural,Y
772,LP001878,Male,No,1.0,Graduate,No,5823,2529.000000,187.0,360.0,1.0,Semiurban,Y
47,LP001144,Male,Yes,0.0,Graduate,No,5821,0.000000,144.0,360.0,1.0,Urban,Y
240,LP001798,Male,Yes,2.0,Graduate,No,5819,5000.000000,120.0,360.0,1.0,Rural,Y
327,LP002082,Male,Yes,0.0,Graduate,Yes,5818,2160.000000,184.0,360.0,1.0,Semiurban,Y
966,LP002907,Male,Yes,0.0,Graduate,No,5817,910.000000,109.0,360.0,1.0,Urban,Y
514,LP002652,Male,No,0.0,Graduate,No,5815,3666.000000,311.0,360.0,1.0,Rural,N
563,LP002821,Male,No,0.0,Not Graduate,Yes,5800,0.000000,132.0,360.0,1.0,Semiurban,Y
599,LP002948,Male,Yes,2.0,Graduate,No,5780,0.000000,192.0,360.0,1.0,Urban,Y
891,LP002550,Female,No,0.0,Graduate,No,5769,0.000000,110.0,180.0,1.0,Semiurban,Y
313,LP002008,Male,Yes,2.0,Graduate,Yes,5746,0.000000,144.0,84.0,NaN,Rural,Y
236,LP001786,Male,Yes,0.0,Graduate,NaN,5746,0.000000,255.0,360.0,NaN,Urban,N
65,LP001225,Male,Yes,0.0,Graduate,No,5726,4595.000000,258.0,360.0,1.0,Semiurban,N
614,LP001015,Male,Yes,0.0,Graduate,No,5720,0.000000,110.0,360.0,1.0,Urban,Y
827,LP002176,Male,No,0.0,Graduate,No,5708,0.000000,150.0,360.0,1.0,Rural,Y
173,LP001594,Male,Yes,0.0,Graduate,No,5708,5625.000000,187.0,360.0,1.0,Semiurban,Y
213,LP001715,Male,Yes,4.0,Not Graduate,Yes,5703,0.000000,130.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,4.0,Graduate,No,5703,0.000000,128.0,360.0,1.0,Urban,Y
89,LP001310,Male,Yes,0.0,Graduate,No,5695,4167.000000,175.0,360.0,1.0,Semiurban,Y
522,LP002692,Male,Yes,4.0,Graduate,Yes,5677,1424.000000,100.0,360.0,1.0,Rural,Y
120,LP001426,Male,Yes,NaN,Graduate,No,5667,2667.000000,180.0,360.0,1.0,Rural,Y
629,LP001099,Male,No,1.0,Graduate,No,5667,0.000000,131.0,360.0,1.0,Urban,Y
887,LP002495,Male,Yes,2.0,Graduate,No,5667,440.000000,130.0,360.0,0.0,Semiurban,N
46,LP001138,Male,Yes,1.0,Graduate,No,5649,0.000000,44.0,360.0,1.0,Urban,Y
654,LP001220,Male,Yes,0.0,Graduate,No,5629,818.000000,100.0,360.0,1.0,Urban,Y
776,LP001909,Male,No,0.0,Graduate,No,5583,0.000000,116.0,360.0,1.0,Urban,Y
118,LP001421,Male,Yes,0.0,Graduate,No,5568,2142.000000,175.0,360.0,1.0,Rural,N
474,LP002524,Male,No,2.0,Graduate,No,5532,4648.000000,162.0,360.0,1.0,Rural,Y
896,LP002566,Female,No,0.0,Graduate,No,5530,0.000000,135.0,360.0,NaN,Urban,Y
177,LP001610,Male,Yes,4.0,Graduate,No,5516,11300.000000,495.0,360.0,0.0,Semiurban,N
944,LP002823,Male,Yes,0.0,Graduate,No,5509,0.000000,143.0,360.0,1.0,Rural,Y
335,LP002106,Male,Yes,NaN,Graduate,Yes,5503,4490.000000,70.0,NaN,1.0,Semiurban,Y
235,LP001784,Male,Yes,1.0,Graduate,No,5500,1260.000000,170.0,360.0,1.0,Rural,Y
353,LP002142,Female,Yes,0.0,Graduate,Yes,5500,0.000000,105.0,360.0,0.0,Rural,N
389,LP002250,Male,Yes,0.0,Graduate,No,5488,0.000000,125.0,360.0,1.0,Rural,Y

# to add a new column in our DF

In [127]:
# the main condition to add new columns is dataframe(number of rows same as number of rows in df)

# lets consider the income f all the people is 2 times

In [128]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')
new_income = 2*cr.ApplicantIncome # new_income is new col

In [129]:
new_income

0       11698
1        9166
2        6000
3        5166
4       12000
5       10834
6        4666
7        6072
8        8012
9       25682
10       6400
11       5000
12       6146
13       3706
14       2598
15       9900
16       7192
17       7020
18       9774
19       5200
20      15320
21      11910
22       5200
23       6730
24       7434
25      19120
26       5598
27       8452
28       2884
29       7500
30       8332
31       6334
32       9384
33       7000
34      25000
35       4550
36       3656
37       7334
38       8332
39       7496
40       7200
41       3600
42       4800
43       7882
44       9390
45       6820
46      11298
47      11642
48       5290
49       8000
50       3856
51       6172
52       8460
53       9232
54      23000
55       5416
56       4264
57       6732
58      16160
59       6714
60       5000
61       6058
62       5218
63       9890
64       8332
65      11452
66       6400
67      21500
68      14200
69       8600
70       6416
71       3750
72       7000
73       9510
74      10532
75       7500
76       7500
77       2000
78       6334
79       6666
80       7692
81       4790
82       2756
83      12000
84       7976
85       4732
86       6666
87       5000
88      17132
89      11390
90       5916
91      12500
92       6546
93       8266
94       7240
95      13564
96       4968
97       3954
98       8376
99       3518
100      8576
101      9686
102     27300
103      9304
104      7632
105      6104
106     22834
107     14666
108      7600
109      4142
110     10632
111      5858
112      7144
113     14902
114     10100
115     29166
116      6334
117      4428
118     11136
119     20816
120     11334
121      8332
122      4274
123      5914
124      8600
125      7384
126     47606
127      7730
128     21026
129     12160
130     40332
131      4028
132      5436
133      6918
134      9790
135      8000
136      9166
137      6632
138     29998
139      8400
140     10084
141     10834
142     13900
143      5396
144     23514
145      4660
146     29732
147      3076
148     20000
149      9720
150     12554
151      5154
152     18332
153      4562
154      6508
155     79998
156     12000
157     19076
158      5960
159      9166
160      3726
161     15866
162      6178
163      8334
164     18646
165      7414
166      9166
167      4878
168      4474
169     16000
170      3640
171    103526
172      7044
173     11416
174      8688
175      6994
176      4090
177     11032
178      7500
179      4666
180     12800
181      3832
182      9200
183     67692
184      7250
185     78294
186      4356
187      4766
188      1348
189     18656
190      9770
191     24000
192     12066
193      7716
194      8382
195      6250
196     16666
197      3814
198      6832
199     22000
200      5200
201      9846
202      7984
203      7000
204      7834
205      8816
206      6488
207      7950
208      4958
209      6836
210     20000
211      6860
212     15574
213     11406
214      6346
215      7700
216       300
217      7454
218     10000
219      8566
220      4442
221      8018
222      5942
223     15156
224     12500
225      6500
226      9470
227     12500
228      9516
229     12800
230      4982
231      7432
232      6378
233     16666
234      6310
235     11000
236     11492
237      6926
238      7624
239      6630
240     11638
241      5020
242      5930
243     12500
244      6812
245     12100
246     19406
247     13216
248      5764
249      3618
250      3336
251      6854
252      5166
253      5322
254     32500
255      6166
256     12090
257     10500
258     29366
259      9862
260     12166
261      4120
262      6962
263     14400
264     10332
265      8190
266      9416
267      8666
268      6836
269      5752
270      6474
271     22292
272      5666
273      5240
274      7800
275      5500
276      7986
277      6206
278     29166
279      8200
280      8106
281      7854
282      4602
283      3622
284     41334
285      6316
286      5200
287      7408
288      8248
289     19016
290      6150
291      8800
292      6306
293     10834
294      4766
295      8832
296     13750
297      9332
298     10000
299      4028
300      3600
301      5750
302     10000
303      3250
304      8000
305      4000
306      7524
307      4800
308     40466
309     15334
310      5834
311      5854
312      5014
313     11492
314      4946
315      6798
316      7434
317      4116
318      7082
319     20000
320      4800
321      8684
322      7202
323      6332
324     30000
325     17332
326      9834
327     11636
328      8666
329      5000
330      8768
331      5870
332      5666
333    126674
334     19666
335     11006
336     10500
337      5000
338      3660
339      8320
340      5294
341      4756
342      9108
343      6346
344      5166
345      4998
346      7046
347      6166
348     12666
349      5250
350     18166
351     17500
352      5332
353     11000
354      4846
355      7626
356     16666
357      7750
358      6000
359     10334
360      9446
361     10000
362      9500
363      6026
364     13644
365     12432
366      5000
367     10248
368     12650
369     39460
370     31518
371     10370
372     18646
373      6124
374      5528
375      9634
376     17500
377      8620
378      6138
379     10782
380      6666
381     11882
382     12000
383     14334
384      9132
385      7334
386      4692
387      6020
388      4666
389     10976
390     18334
391     19008
392      5166
393      3986
394      6200
395      6552
396      6360
397      6066
398      7804
399      3000
400      5778
401      5510
402      5000
403      3926
404     14882
405      9094
406      4334
407      4426
408     16600
409    162000
410      7734
411     12512
412     12192
413      4506
414      4298
415      5990
416      5200
417      3200
418      2050
419      6492
420     11658
421      5440
422      3640
423     14500
424     29760
425      5332
426      9212
427     11870
428      5840
429      5434
430     17248
431     13000
432     25752
433      4850
434      7500
435     20094
436      3852
437      4426
438     20832
439     14284
440      7320
441     15802
442      9414
443     75438
444     14666
445      6932
446      9304
447      7078
448      6680
449      5538
450      4618
451      3916
452      7896
453      4966
454     14170
455      7718
456      8602
457      7416
458      8708
459     16668
460      4166
461     15480
462      6030
463     10382
464      8332
465     12000
466      5894
467     33384
468       420
469      8666
470      6900
471      5306
472      9382
473      5000
474     11064
475     33050
476     13400
477      5746
478     33334
479      5894
480      8700
481      6190
482      4166
483     21666
484     16666
485      3916
486      7094
487     36666
488      9166
489      4870
490      5398
491     10666
492      7382
493     34526
494      7194
495      6652
496      5200
497      9250
498      5790
499     12566
500      1290
501      6318
502      9730
503      8100
504      7628
505      7020
506     41666
507      7166
508      4958
509     26524
510      7196
511     12130
512      6566
513      4260
514     11630
515      6932
516      4062
517      6148
518      9366
519      6800
520      4384
521      5000
522     11354
523     15896
524      9360
525     35000
526      7550
527     10570
528      5358
529     13566
530      2050
531      8562
532      7176
533     22500
534     36330
535      5100
536     12266
537      7234
538      5834
539     12834
540      9216
541      4276
542      7304
543      4478
544      6034
545      5536
546      6716
547      5052
548     10000
549      5570
550     13266
551      4984
552      6666
553      4908
554      7186
555     10936
556      5334
557     20278
558      7774
559      8360
560      7350
561     38968
562     11846
563     11600
564     17598
565      8934
566      6666
567      6800
568      4756
569      6332
570      6834
571     10232
572     33332
573     12250
574     12812
575      6318
576      6174
577      6458
578      3564
579      6364
580     13080
581      3672
582      6332
583      3760
584      5574
585      8566
586      4594
587      4330
588      9500
589      5452
590      6000
591     12000
592     18714
593      7718
594     32240
595      7666
596     12766
597      5974
598     19926
599     11560
600       832
601      5788
602     11406
603      7352
604     24000
605      4800
606      6800
607      7974
608      6464
609      5800
610      8212
611     16144
612     15166
613      9166
614     11440
615      6152
616     10000
617      4680
618      6552
619      4330
620      4452
621      7762
622     27266
623      4800
624      6182
625      4370
626      8332
627     24346
628      9332
629     11334
630      9166
631      7572
632     18452
633      2600
634      3776
635      4166
636      7818
637      7530
638     10800
639         0
640      8726
641     15000
642      7544
643      5884
644      4956
645     12500
646      6536
647      5566
648      5480
649      6300
650     14700
651      4534
652     11666
653      7286
654     11258
655      7288
656      3500
657     13000
658      7332
659      8520
660      8326
661      4712
662     13584
663     16000
664      4838
665      7000
666      7000
667      8232
668     10586
669      5500
670      8804
671      7226
672      5558
673      9440
674      4830
675     14032
676      9936
677      4202
678      8980
679      5834
680      9400
681      6890
682     15332
683      4916
684      6500
685      8926
686      8166
687      7800
688      9500
689      7166
690      6378
691     12712
692      6826
693     15900
694      7658
695    145058
696      8272
697     16898
698      8912
699      9270
700      7142
701      6132
702      6470
703     10116
704      6376
705     27036
706      8728
707      9532
708      9218
709     12520
710      6666
711      7000
712     19438
713     13670
714      8904
715      4524
716      7802
717      5374
718      4486
719      6834
720      3192
721      9026
722      9000
723      9046
724      9484
725      8164
726      6834
727      5844
728      8334
729      8486
730         0
731      3032
732      3524
733      1448
734      6250
735      4666
736      6700
737      5000
738     25000
739      9334
740     13000
741     15000
742      6146
743      6642
744      6666
745      6782
746      6686
747      7240
748      8000
749      8516
750      9000
751      4028
752      6666
753      8166
754      9454
755      6178
756     13588
757     64000
758     21780
759     25882
760      6552
761     17406
762      9484
763     11800
764      6142
765      5566
766     10000
767      4926
768      9710
769      3198
770      8492
771      8666
772     11646
773     15790
774      8300
775      5928
776     11166
777      5416
778      6360
779      4536
780      2282
781      6084
782      3500
783      7128
784      7916
785      8966
786     10450
787      6034
788      4862
789      9824
790      5000
791      5836
792     10256
793     30624
794      7916
795      8668
796      8716
797      8000
798     20332
799      8966
800      9042
801     18334
802     26166
803     15748
804      8666
805      8166
806      7570
807      5308
808     20000
809     11666
810      9592
811      4000
812      5080
813      3800
814     17412
815      5710
816      6032
817      6318
818      3874
819      5226
820      9920
821      6148
822      8426
823      4076
824      4724
825     10666
826     10768
827     11416
828      7508
829      5828
830      5494
831     15660
832      7014
833      7494
834      4332
835      7000
836      5792
837     10124
838     10368
839      5090
840      5106
841      6872
842      4824
843     10360
844     29822
845      5720
846      2346
847     15200
848      4314
849      4462
850      4548
851     12332
852      5026
853      8666
854      7688
855      7774
856      7020
857      5078
858      4214
859      6372
860     10000
861     20000
862      7886
863      5850
864      6484
865      7726
866      8056
867      8020
868      7438
869      5716
870      7666
871      6666
872      6014
873      3700
874      5584
875      5964
876      6834
877     37680
878      5990
879      7158
880      7670
881      7708
882     11666
883      7016
884      3270
885      6666
886     49594
887     11334
888      7000
889      5546
890     13000
891     11538
892      7268
893     58334
894      4332
895     10000
896     11060
897     18000
898     20000
899     17500
900      4314
901      3944
902      9966
903     16666
904      7334
905      6332
906      6542
907      4482
908      3584
909      5332
910     12956
911      7616
912      7458
913      8240
914     15000
915     12600
916     29974
917      1140
918      5200
919      5466
920     15000
921      7718
922     13650
923      7416
924     10628
925      4732
926      4132
927     10000
928      7534
929     15718
930      8566
931      3400
932      9536
933      6166
934      5334
935      3294
936      6800
937     32000
938     10666
939      5750
940      5200
941     10082
942     13916
943      7000
944     11018
945     19398
946      7242
947      9418
948      3032
949      4800
950      6030
951      4584
952      4720
953      8666
954      5246
955      7944
956      7044
957      9400
958     13716
959     16668
960      6782
961      5736
962      6836
963      5000
964     17334
965      4566
966     11634
967     10238
968     10632
969     15206
970      7582
971      5000
972      6264
973      8000
974     17100
975      4538
976      8018
977      8316
978      6500
979     10000
980     18400
Name: ApplicantIncome, dtype: int64

In [130]:
cr['New_Income_col'] = new_income

In [131]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Income_col
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [132]:
# Another way to add column is to use concat

In [133]:
cr_new = pd.concat([cr, new_income], axis = 1)

In [134]:
cr_new.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Income_col,ApplicantIncome
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000,12000

In [135]:
# how to rename a columns

In [136]:
cr.rename(columns = {'ApplicantIncome':'AppInce'}, inplace=True)

In [137]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,AppInce,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Income_col
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [138]:
# i can change name of ore than 1 column in single line

In [139]:
cr.rename(columns={'Gender':'Gen'}, inplace= True)

In [140]:
cr.rename(columns={'Education':'Edu', 'Self_Employed':'Self_Emp'}, inplace= True)

In [141]:
cr.head()

,Loan_ID,Gen,Married,Dependents,Edu,Self_Emp,AppInce,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Income_col
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [142]:
# another way to change column name without using column Name

In [143]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')
cr.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N

In [144]:
# Lets Take Gennder and Education col

In [145]:
cr.rename(columns={cr.columns[1]:'Gen',  cr.columns[4]:'Edu'}, inplace= True)
cr.head()

,Loan_ID,Gen,Married,Dependents,Edu,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [146]:
cr = pd.read_csv('C:/Users/shubh/Downloads/CreditRisk.csv')
new_income = 2*cr.ApplicantIncome # new_income is new c
cr_new = pd.concat([cr, new_income], axis = 1)
cr_new.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,ApplicantIncome
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [147]:
cr_new.rename(columns={cr_new.columns[-1]:'New_Appli_Income'},inplace = True)

In [148]:
cr_new.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,New_Appli_Income,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Appli_Income
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [149]:
# how to change the names of columns when duplicate name exist.

In [150]:
new_income = 2*cr.ApplicantIncome # new_income is new c
cr_new = pd.concat([cr, new_income], axis = 1)
cr_new.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,ApplicantIncome
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [151]:
cr_new.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'ApplicantIncome'],
      dtype='object')

In [152]:
type(cr_new.columns)

pandas.core.indexes.base.Index

In [154]:
l1 = list(cr_new.columns)
# l1

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status',
 'ApplicantIncome']

In [155]:
len(l1)

14

In [156]:
l1[13] = 'New_Appli_Income'

In [157]:
cr_new.columns = l1

In [158]:
cr_new.head(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Appli_Income
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166

In [167]:
import pandas as pd

In [190]:
date_time = pd.DataFrame({'date':('2018-1-28', '2019-10-28')})

In [191]:
date_time

         date
0   2018-1-28
1  2019-10-28

In [192]:
date_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2 non-null      object
dtypes: object(1)
memory usage: 144.0+ bytes

In [193]:
date_time.date = pd.to_datetime(data_time.date)

# date_time is name of DF and .date is column we are selecting from the data Frame

## using pd.to_datetime convert object column to date time format

In [194]:
date_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 144.0 bytes

In [195]:
date_time['date'].dt.year

0    2018
1    2019
Name: date, dtype: int64

In [196]:
date_time['date'].dt.month

0     1
1    10
Name: date, dtype: int64

In [197]:
date_time['date'].dt.week

<ipython-input-197-abb7d72d7bc9>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  date_time['date'].dt.week

0     4
1    44
Name: date, dtype: int64

In [198]:
date_time['date'].dt.day

0    28
1    28
Name: date, dtype: int64

In [199]:
date_time['Year'] = date_time['date'].dt.year

In [200]:
date_time

        date  Year
0 2018-01-28  2018
1 2019-10-28  2019

In [201]:
date_time['Month'] = data_time['date'].dt.month

In [202]:
date_time

        date  Year  Month
0 2018-01-28  2018      1
1 2019-10-28  2019     10

In [203]:
date_time['Day'] = date_time['date'].dt.day

In [204]:
date_time

        date  Year  Month  Day
0 2018-01-28  2018      1   28
1 2019-10-28  2019     10   28

In [211]:
df_date_time = pd.DataFrame({'DT':('2018-12-28 12:24:59',
                                   '2019-05-9 2:10:25',
                                   '2019-12-31 22:10:25',
                                   '2017-01-01 9:01:20',
                                  '2019-07-03 22:10:25')})

In [214]:
df_date_time

                    DT
0  2018-12-28 12:24:59
1    2019-05-9 2:10:25
2  2019-12-31 22:10:25
3   2017-01-01 9:01:20
4  2019-07-03 22:10:25

In [217]:
df_date_time.DT = pd.to_datetime(df_date_time.DT)

In [218]:
df_date_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DT      5 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 168.0 bytes

In [220]:
df_date_time['Year'] = df_date_time.DT.dt.year
df_date_time['Month_of_year'] = df_date_time.DT.dt.month
df_date_time['Day_of_Month'] = df_date_time.DT.dt.day
df_date_time['Hour_of_Day'] = df_date_time.DT.dt.hour
df_date_time['Minutes'] = df_date_time.DT.dt.minute
df_date_time['second'] = df_date_time.DT.dt.second

In [221]:
df_date_time

,DT,Year,Month_of_year,Day_of_Month,Hour_of_Day,Minutes,second
0,2018-12-28 12:24:59,2018,12,28,12,24,59
1,2019-05-09 02:10:25,2019,5,9,2,10,25
2,2019-12-31 22:10:25,2019,12,31,22,10,25
3,2017-01-01 09:01:20,2017,1,1,9,1,20
4,2019-07-03 22:10:25,2019,7,3,22,10,25

In [222]:
#lets create a dataframe which doees noot dates in proper format

In [223]:
invalid_time = pd.DataFrame({'DT':('20150112',
                                  '4570',
                                  '201A/10/11',
                                  '20160919')})

In [224]:
invalid_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DT      4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes

In [228]:
invalid_time.DT = pd.to_datetime(invalid_time.DT, errors = 'ignore') # raise means error will be shown and executions stops

In [229]:
invalid_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DT      4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes

In [230]:
invalid_time.DT = pd.to_datetime(invalid_time.DT, errors = 'coerce')
invalid_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DT      2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 160.0 bytes

In [231]:
invalid_time.DT

0   2015-01-12
1          NaT
2          NaT
3   2016-09-19
Name: DT, dtype: datetime64[ns]

In [232]:
invalid_time.DT = invalid_time.DT.fillna('2015-01-01')

In [233]:
invalid_time

                    DT
0  2015-01-12 00:00:00
1           2015-01-01
2           2015-01-01
3  2016-09-19 00:00:00